ame: "MR pipeline for 'main'"
run-name: ${{ github.actor }} created MR

on:
  # run if pull_request is targeting 'main'
  pull_request:
    types: [closed]
    branches:    
        - main

jobs:
  stg:
    runs-on: ubuntu-latest
    environment: stg
    if: ${{ github.event.pull_request.merged == true }}

    steps:
        - name: Checkout Branch
          uses: actions/checkout@v3
          with:
            ref: main
            token: ${{ secrets.GITHUB_TOKEN }}

        - name: Fetch all branches (including stg)
          run: git fetch origin stg
        
        - name: Deploy to Staging
          run: |
            echo "Deploying to staging environment..."
            echo "Step 1: Rebase Staging Branch with Main"
            git checkout stg
            git merge main
            echo "Step 2: Push Staging Branch"
            git push
            echo "Deployment to staging completed successfully."
  
  prod:
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ github.event.pull_request.merged == true }}
    needs: stg

    steps:
        - uses: actions/checkout@v3
        - run: |
            echo "Deploying to production environment..."
            git checkout stg
            git pull
            git checkout prod
            git pull
            git rebase stg
            git push origin prod --force
            echo "Deployment to production completed successfully."
