name: "MR pipeline for 'main'"
run-name: ${{ github.actor }} created MR

on:
  # run if pull_request is targeting 'main'
  pull_request:
    types: [closed]
    branches:    
        - main

jobs:
  stg:
    runs-on: ubuntu-latest
    environment: stg
    if: ${{ github.event.pull_request.merged == true }}

    steps:
        - name: Checkout Branch
          uses: actions/checkout@v3
          with:
            ref: main
            token: ${{ secrets.GITHUB_TOKEN }}
            fetch-depth: 0

        - name: Fetch all branches (including stg)
          run: git fetch origin stg
        
        - name: Deploy to Staging
          run: |
            echo "Deploying to staging environment..."
            git checkout stg
            git merge main
            git push
            echo "Deployment to staging completed successfully."
  
  prod:
    runs-on: ubuntu-latest
    environment: prod
    if: ${{ github.event.pull_request.merged == true }}
    needs: stg

    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
        with:
          ref: stg
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0
      
      - name: Fetch all branches (including prod)
        run: git fetch origin prod
      
      - name: Deploy to Production
        run: |
          echo "Deploying to production environment..."
          git checkout prod
          git merge stg
          git push
          echo "Deployment to production completed successfully."
